from app import app, db
from app.models import Teammate, EventCard

with app.app_context():
    # clear existing data so we don't get duplicates if run multiple times
    EventCard.query.delete()
    Teammate.query.delete()

    # --- Create teammates ---
    teammates = [
        Teammate(
            name='Josh',
            role='The Ghost',
            description='Disappears without warning. Last seen 4 days ago. May or may not resurface before the deadline.',
            image='josh.png',
            emoji='👻'
        ),
        Teammate(
            name='Priya',
            role='The Overachiever',
            description='Rewrites your work at 2am. Means well, but absolutely exhausting.',
            image='priya.png',
            emoji='🦅'
        ),
        Teammate(
            name='David',
            role='The Slacker',
            description='Will submit something. Just lower your expectations... By a lot.',
            image='david.png',
            emoji='😴'
        ),
        Teammate(
            name='Sheldon',
            role='The Know-It-All',
            description="Insists they're always right and knows what they're doing but in reality… they don't.",
            image='sheldon.png',
            emoji='🤓'
        ),
        Teammate(
            name='Lucy',
            role='The Social Butterfly',
            description="More interested in sharing memes than the fact that the deadline is within 3 days.",
            image='lucy.png',
            emoji='🦋'
        ),
    ]

    db.session.add_all(teammates)
    db.session.commit()

    josh, priya, david, sheldon, lucy = teammates

     # --- Create event cards ---
    events = [

        # PRIYA EVENTS
        EventCard(
            title='The Unsolicited Rewrite',
            description="Priya rewrote your entire introduction section at 2am without telling anyone. She says it was 'not up to standard.' Your original draft is gone.",
            teammate=priya,
            option_a='Revert to your original draft',
            option_a_morale=-10,
            option_a_progress=+5,
            option_b='Keep her version and adapt your sections',
            option_b_morale=+10,
            option_b_progress=-10,
            option_c='Call an emergency group meeting to discuss',
            option_c_morale=+5,
            option_c_progress=-5,
        ),
        EventCard(
            title='The Unsolicited Meeting',
            description="Priya scheduled a 9am meeting for tomorrow with a 14 point agenda. Nobody was consulted. The calendar invite was sent at midnight.",
            teammate=priya,
            option_a='Attend the full meeting and go through everything',
            option_a_morale=-15,
            option_a_progress=+15,
            option_b='Suggest cutting it down to 3 key points',
            option_b_morale=+5,
            option_b_progress=+5,
            option_c='Skip it entirely',
            option_c_morale=-10,
            option_c_progress=0,
        ),
        EventCard(
            title='The Peer Review Nobody Asked For',
            description="Priya sends everyone a detailed written critique of their sections with a rubric style rating out of 10. Yours got a 5. She expects revisions by tonight.",
            teammate=priya,
            option_a='Take the feedback seriously and revise everything',
            option_a_morale=-10,
            option_a_progress=+15,
            option_b='Revise only the most critical parts',
            option_b_morale=0,
            option_b_progress=+8,
            option_c='Push back and defend your work',
            option_c_morale=+10,
            option_c_progress=0,
        ),
        EventCard(
            title='The Scope Creep',
            description="Priya suggests adding three entirely new sections to make the report 'more comprehensive.' The deadline is in 4 days. Everyone is already stretched thin.",
            teammate=priya,
            option_a='Agree and divide the new sections among the group',
            option_a_morale=-15,
            option_a_progress=-20,
            option_b='Agree to add just one small section',
            option_b_morale=+5,
            option_b_progress=-8,
            option_c='Shut it down and stick to the original scope',
            option_c_morale=+10,
            option_c_progress=+5,
        ),
        EventCard(
            title='The Restructure Spiral',
            description="Priya has been online for 19 hours straight and is now suggesting the entire report layout needs to be restructured from scratch. She has already started making changes without asking anyone.",
            teammate=priya,
            option_a='Trust her and help restructure',
            option_a_morale=-10,
            option_a_progress=-25,
            option_b='Let her restructure her sections only',
            option_b_morale=+5,
            option_b_progress=-8,
            option_c='Lock the document and tell everyone to stop editing',
            option_c_morale=-15,
            option_c_progress=+10,
        ),

        # JOSH EVENTS
        EventCard(
            title='The Disappearing Act',
            description="Josh has not responded to any messages for 4 days. His section was due yesterday. The group chat shows he has read every single message.",
            teammate=josh,
            option_a='Do his section yourself',
            option_a_morale=-20,
            option_a_progress=+15,
            option_b='Send him a firm deadline ultimatum',
            option_b_morale=-10,
            option_b_progress=0,
            option_c='Redistribute his tasks among the group',
            option_c_morale=-15,
            option_c_progress=+10,
        ),
        EventCard(
            title='The Classic Return',
            description="Josh reappears after 5 days of silence with a 'Hey guys. What are we doing again?' in the group chat.",
            teammate=josh,
            option_a='Catch him up and reassign him tasks',
            option_a_morale=-15,
            option_a_progress=+10,
            option_b='Passive aggressively send him the entire chat history',
            option_b_morale=+10,
            option_b_progress=0,
            option_c='Tell him its too late and split his work among yourselves',
            option_c_morale=-10,
            option_c_progress=+5,
        ),
        EventCard(
            title='The Empty Promise',
            description="Josh finally responds and says 'I'll have my part done by tonight, don't stress.' It is now the next morning. Nothing has been submitted.",
            teammate=josh,
            option_a='Do his work yourself, again',
            option_a_morale=-20,
            option_a_progress=+15,
            option_b='Wait another day and give him one last chance',
            option_b_morale=-10,
            option_b_progress=-10,
            option_c='Escalate the issue to your lecturer',
            option_c_morale=+5,
            option_c_progress=0,
        ),
        EventCard(
            title='The Half Baked Contribution',
            description="Josh finally drops a half finished document in the group chat with the message 'here's my part sorry was busy.' It is poorly written, barely covers the brief, and needs significant work.",
            teammate=josh,
            option_a='Polish it and include it',
            option_a_morale=-15,
            option_a_progress=+10,
            option_b='Return it to him and demand a proper version',
            option_b_morale=+10,
            option_b_progress=-15,
            option_c='Rewrite it entirely yourself',
            option_c_morale=-20,
            option_c_progress=+5,
        ),
        EventCard(
            title='The Guilt Trip',
            description="Josh messages the group saying he has been dealing with personal issues and apologises for being absent. He promises to make it up to everyone.",
            teammate=josh,
            option_a='Empathise and give him another chance',
            option_a_morale=+15,
            option_a_progress=0,
            option_b='Acknowledge it but keep his workload minimal',
            option_b_morale=+5,
            option_b_progress=+5,
            option_c='Tell him the group has already covered his work',
            option_c_morale=-10,
            option_c_progress=+10,
        ),

        # DAVID EVENTS
        EventCard(
            title='The Ch*tGPT Submission',
            description="David submits his section and at the very bottom it reads 'Generated by Ch*tGPT.' The formatting is wrong, the references are fake, and it does not match the brief at all.",
            teammate=david,
            option_a='Rewrite it entirely yourself',
            option_a_morale=-20,
            option_a_progress=+15,
            option_b='Send it back to David and demand a proper version',
            option_b_morale=-5,
            option_b_progress=-10,
            option_c='Edit it enough to make it passable',
            option_c_morale=-10,
            option_c_progress=+5,
        ),
        EventCard(
            title='The Bare Minimum',
            description="David submits three bullet points for a section that was supposed to be 500 words. His message reads 'I covered the main points, should be fine.'",
            teammate=david,
            option_a='Expand it yourself to meet the word count',
            option_a_morale=-15,
            option_a_progress=+10,
            option_b='Return it to David with specific instructions',
            option_b_morale=0,
            option_b_progress=-5,
            option_c='Leave it and hope the marker does not notice',
            option_c_morale=+5,
            option_c_progress=-15,
        ),
        EventCard(
            title='The Selective Responder',
            description="David responds to every fun message in the group chat instantly but has left your last three task related messages on read for two days.",
            teammate=david,
            option_a='Call him out publicly in the group chat',
            option_a_morale=+10,
            option_a_progress=0,
            option_b='Message him privately and firmly',
            option_b_morale=+5,
            option_b_progress=+5,
            option_c='Assign his tasks to someone else without telling him',
            option_c_morale=-10,
            option_c_progress=+10,
        ),
        EventCard(
            title='The Excuse Machine',
            description="David says he could not start his section because he was waiting for someone else to finish theirs first. Nobody told him to wait. His section is independent.",
            teammate=david,
            option_a='Accept his excuse and extend his deadline',
            option_a_morale=-5,
            option_a_progress=-10,
            option_b='Call out the excuse and set a firm new deadline',
            option_b_morale=0,
            option_b_progress=+5,
            option_c='Do his section yourself and move on',
            option_c_morale=-15,
            option_c_progress=+15,
        ),
        EventCard(
            title='The Section Swap',
            description="David messages the group asking if he can swap his assigned section for an easier one because he 'did not realise how much work his involved.' He has not started either section.",
            teammate=david,
            option_a='Agree and swap sections to keep the peace',
            option_a_morale=-5,
            option_a_progress=-15,
            option_b='Refuse but offer to help him with his section',
            option_b_morale=+5,
            option_b_progress=+5,
            option_c='Refuse and tell him to figure it out',
            option_c_morale=-15,
            option_c_progress=+10,
        ),

        # SHELDON EVENTS
        EventCard(
            title='The Wrong Expert',
            description="Sheldon insists the report structure you all agreed on is wrong and rewrites the outline based on a YouTube video he watched. He has not read the actual rubric.",
            teammate=sheldon,
            option_a='Follow his structure to avoid conflict',
            option_a_morale=-5,
            option_a_progress=-15,
            option_b='Show him the rubric and correct him calmly',
            option_b_morale=+5,
            option_b_progress=+10,
            option_c='Ignore him and stick to the original structure',
            option_c_morale=-10,
            option_c_progress=+5,
        ),
        EventCard(
            title='The Overruler',
            description="During the group meeting Sheldon talks over everyone and dismisses every idea that is not his. The meeting has been going for 90 minutes and nothing has been decided.",
            teammate=sheldon,
            option_a='Let him take the lead to end the meeting faster',
            option_a_morale=-15,
            option_a_progress=+5,
            option_b='Firmly redirect the conversation to a vote',
            option_b_morale=+5,
            option_b_progress=+10,
            option_c='End the meeting and continue over chat instead',
            option_c_morale=+10,
            option_c_progress=-5,
        ),
        EventCard(
            title='The Confident Mistake',
            description="Sheldon submitted his section with completely wrong data. When corrected he insists his figures are right and the source you found is unreliable.",
            teammate=sheldon,
            option_a='Override him and fix the data yourself',
            option_a_morale=-15,
            option_a_progress=+15,
            option_b='Find a second source to prove the correction',
            option_b_morale=0,
            option_b_progress=+10,
            option_c='Leave his section as is to avoid the argument',
            option_c_morale=+5,
            option_c_progress=-20,
        ),
        EventCard(
            title='The Unsolicited Takeover',
            description="Sheldon announces he will be taking over as project manager because he feels the group lacks direction. Nobody voted for this. Nobody asked for this.",
            teammate=sheldon,
            option_a='Let him take over — at least someone is leading',
            option_a_morale=-15,
            option_a_progress=+5,
            option_b='Propose a democratic vote on roles',
            option_b_morale=+15,
            option_b_progress=0,
            option_c='Firmly tell him roles were already decided',
            option_c_morale=+5,
            option_c_progress=+5,
        ),
        EventCard(
            title='The Citation Argument',
            description="Sheldon insists every reference in the report needs to be in a format he invented himself. It does not match APA, MLA, or any recognised style. He will not budge.",
            teammate=sheldon,
            option_a='Use his format to keep the peace',
            option_a_morale=-5,
            option_a_progress=-10,
            option_b='Show him the required referencing guide',
            option_b_morale=+5,
            option_b_progress=+10,
            option_c='Secretly fix all references to the correct format after submission',
            option_c_morale=+10,
            option_c_progress=+15,
        ),

        # LUCY EVENTS
        EventCard(
            title='The Side Quest',
            description="Lucy suggests the group takes a break and goes for lunch together because 'team bonding is important.' The deadline is in 3 days and two sections are unfinished.",
            teammate=lucy,
            option_a='Go along with it — morale has been low anyway',
            option_a_morale=+20,
            option_a_progress=-10,
            option_b='Suggest a shorter 30 minute break instead',
            option_b_morale=+10,
            option_b_progress=-5,
            option_c='Decline and stay focused on the work',
            option_c_morale=-10,
            option_c_progress=+10,
        ),
        EventCard(
            title='The Meme Flood',
            description="Lucy has sent 23 memes in the group chat today. Every notification you get pulls your attention away from writing. Your section is due tomorrow.",
            teammate=lucy,
            option_a='Mute the chat and grind through your work',
            option_a_morale=-10,
            option_a_progress=+15,
            option_b='Laugh along and join in for a bit',
            option_b_morale=+15,
            option_b_progress=-10,
            option_c='Ask the group to keep the chat focused',
            option_c_morale=0,
            option_c_progress=+5,
        ),
        EventCard(
            title='The Networking Detour',
            description="Lucy spent the afternoon connecting with people on LinkedIn and writing her personal bio instead of working on her assigned section. She says it is 'career development.'",
            teammate=lucy,
            option_a='Do her section yourself',
            option_a_morale=-15,
            option_a_progress=+10,
            option_b='Remind her the section is due and offer to help',
            option_b_morale=+5,
            option_b_progress=+5,
            option_c='Tell her career development can wait until after submission',
            option_c_morale=-5,
            option_c_progress=+8,
        ),
        EventCard(
            title='The Optimism Problem',
            description="Lucy tells the group to stop stressing because she thinks the project is going well and everyone deserves a break. She logs off to watch Netflix. Several sections are still incomplete.",
            teammate=lucy,
            option_a='Cover her work yourself to stay on track',
            option_a_morale=-20,
            option_a_progress=+15,
            option_b='Send a progress update showing how much is left',
            option_b_morale=0,
            option_b_progress=+5,
            option_c='Let it go and see if she figures it out herself',
            option_c_morale=-5,
            option_c_progress=-15,
        ),
        EventCard(
            title='The Sudden Realisation',
            description="Lucy messages the group in a panic saying she completely forgot about her assigned section and has not started it at all. She has been active on social media all week.",
            teammate=lucy,
            option_a='Split her section among the group and power through',
            option_a_morale=-20,
            option_a_progress=+10,
            option_b='Give her a strict internal deadline to submit something',
            option_b_morale=-10,
            option_b_progress=+5,
            option_c='Submit without her section and note it in the report',
            option_c_morale=+5,
            option_c_progress=-15,
        ),
    ]

    db.session.add_all(events)
    db.session.commit()
    print('Database seeded successfully!')