"""initial

Revision ID: 8281c4faa1a9
Revises: 
Create Date: 2026-05-08 00:02:56.943785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8281c4faa1a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teammate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('teammate_id', sa.Integer(), nullable=True),
    sa.Column('option_a', sa.String(length=200), nullable=True),
    sa.Column('option_a_morale', sa.Integer(), nullable=True),
    sa.Column('option_a_progress', sa.Integer(), nullable=True),
    sa.Column('option_b', sa.String(length=200), nullable=True),
    sa.Column('option_b_morale', sa.Integer(), nullable=True),
    sa.Column('option_b_progress', sa.Integer(), nullable=True),
    sa.Column('option_c', sa.String(length=200), nullable=True),
    sa.Column('option_c_morale', sa.Integer(), nullable=True),
    sa.Column('option_c_progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teammate_id'], ['teammate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_card')
    op.drop_table('teammate')
    # ### end Alembic commands ###
